// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InfinityListModuleScssNamespace {
  export interface IInfinityListModuleScss {
    holder: string;
    item: string;
    root: string;
    shortProductCard: string;
  }
}

declare const InfinityListModuleScssModule: InfinityListModuleScssNamespace.IInfinityListModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InfinityListModuleScssNamespace.IInfinityListModuleScss;
};

export = InfinityListModuleScssModule;
