// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalPortalModuleScssNamespace {
  export interface IModalPortalModuleScss {
    background: string;
    buttonClose: string;
    modalContent: string;
  }
}

declare const ModalPortalModuleScssModule: ModalPortalModuleScssNamespace.IModalPortalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ModalPortalModuleScssNamespace.IModalPortalModuleScss;
};

export = ModalPortalModuleScssModule;
