// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AuthorizationFormModuleScssNamespace {
  export interface IAuthorizationFormModuleScss {
    form: string;
    formInput: string;
  }
}

declare const AuthorizationFormModuleScssModule: AuthorizationFormModuleScssNamespace.IAuthorizationFormModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AuthorizationFormModuleScssNamespace.IAuthorizationFormModuleScss;
};

export = AuthorizationFormModuleScssModule;
