// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonModuleScssNamespace {
  export interface IButtonModuleScss {
    button: string;
    large: string;
    medium: string;
    small: string;
  }
}

declare const ButtonModuleScssModule: ButtonModuleScssNamespace.IButtonModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonModuleScssNamespace.IButtonModuleScss;
};

export = ButtonModuleScssModule;
