// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonLanguageModuleScssNamespace {
  export interface IButtonLanguageModuleScss {
    story: string;
    storyDark: string;
  }
}

declare const ButtonLanguageModuleScssModule: ButtonLanguageModuleScssNamespace.IButtonLanguageModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonLanguageModuleScssNamespace.IButtonLanguageModuleScss;
};

export = ButtonLanguageModuleScssModule;
