// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductFormModuleScssNamespace {
  export interface IProductFormModuleScss {
    form: string;
    formInput: string;
  }
}

declare const ProductFormModuleScssModule: ProductFormModuleScssNamespace.IProductFormModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductFormModuleScssNamespace.IProductFormModuleScss;
};

export = ProductFormModuleScssModule;
