// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonModuleSassNamespace {
  export interface IButtonModuleSass {
    button: string;
    large: string;
    medium: string;
    primary: string;
    secondary: string;
    small: string;
  }
}

declare const ButtonModuleSassModule: ButtonModuleSassNamespace.IButtonModuleSass & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonModuleSassNamespace.IButtonModuleSass;
};

export = ButtonModuleSassModule;
