// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonExampleModuleScssNamespace {
  export interface IButtonExampleModuleScss {
    button: string;
    large: string;
    medium: string;
    primary: string;
    secondary: string;
    small: string;
  }
}

declare const ButtonExampleModuleScssModule: ButtonExampleModuleScssNamespace.IButtonExampleModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonExampleModuleScssNamespace.IButtonExampleModuleScss;
};

export = ButtonExampleModuleScssModule;
