// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace HeaderExampleModuleScssNamespace {
  export interface IHeaderExampleModuleScss {
    'storybook-header': string;
    welcome: string;
  }
}

declare const HeaderExampleModuleScssModule: HeaderExampleModuleScssNamespace.IHeaderExampleModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderExampleModuleScssNamespace.IHeaderExampleModuleScss;
};

export = HeaderExampleModuleScssModule;
