// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageModuleScssNamespace {
  export interface IPageModuleScss {
    'storybook-page': string;
    tip: string;
    'tip-wrapper': string;
  }
}

declare const PageModuleScssModule: PageModuleScssNamespace.IPageModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PageModuleScssNamespace.IPageModuleScss;
};

export = PageModuleScssModule;
