// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageExampleModuleScssNamespace {
  export interface IPageExampleModuleScss {
    storybookPage: string;
    tip: string;
    tipWrapper: string;
  }
}

declare const PageExampleModuleScssModule: PageExampleModuleScssNamespace.IPageExampleModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PageExampleModuleScssNamespace.IPageExampleModuleScss;
};

export = PageExampleModuleScssModule;
