// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductCartModuleScssNamespace {
  export interface IProductCartModuleScss {
    shortProductCard: string;
  }
}

declare const ProductCartModuleScssModule: ProductCartModuleScssNamespace.IProductCartModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductCartModuleScssNamespace.IProductCartModuleScss;
};

export = ProductCartModuleScssModule;
