// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CollapseModuleScssNamespace {
  export interface ICollapseModuleScss {
    collapse: string;
  }
}

declare const CollapseModuleScssModule: CollapseModuleScssNamespace.ICollapseModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CollapseModuleScssNamespace.ICollapseModuleScss;
};

export = CollapseModuleScssModule;
