// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductMainModuleScssNamespace {
  export interface IProductMainModuleScss {
    'storybook-page': string;
    tip: string;
    'tip-wrapper': string;
  }
}

declare const ProductMainModuleScssModule: ProductMainModuleScssNamespace.IProductMainModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductMainModuleScssNamespace.IProductMainModuleScss;
};

export = ProductMainModuleScssModule;
