// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonThemeModuleScssNamespace {
  export interface IButtonThemeModuleScss {
    story: string;
    storyDark: string;
  }
}

declare const ButtonThemeModuleScssModule: ButtonThemeModuleScssNamespace.IButtonThemeModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonThemeModuleScssNamespace.IButtonThemeModuleScss;
};

export = ButtonThemeModuleScssModule;
