// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductShortModuleScssNamespace {
  export interface IProductShortModuleScss {
    buttonContainer: string;
    description: string;
    image: string;
    imageContainer: string;
    infoContainer: string;
    name: string;
    noImage: string;
    price: string;
    shortProductCard: string;
  }
}

declare const ProductShortModuleScssModule: ProductShortModuleScssNamespace.IProductShortModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductShortModuleScssNamespace.IProductShortModuleScss;
};

export = ProductShortModuleScssModule;
