// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProductShortModuleScssNamespace {
  export interface IProductShortModuleScss {
    'button-container': string;
    description: string;
    image: string;
    'image-container': string;
    'info-container': string;
    name: string;
    'no-image': string;
    price: string;
    'short-product-card': string;
  }
}

declare const ProductShortModuleScssModule: ProductShortModuleScssNamespace.IProductShortModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProductShortModuleScssNamespace.IProductShortModuleScss;
};

export = ProductShortModuleScssModule;
