// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalButtonModuleScssNamespace {
  export interface IModalButtonModuleScss {
    background: string;
    buttonClose: string;
    modalContent: string;
  }
}

declare const ModalButtonModuleScssModule: ModalButtonModuleScssNamespace.IModalButtonModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ModalButtonModuleScssNamespace.IModalButtonModuleScss;
};

export = ModalButtonModuleScssModule;
