// Autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CustomButtonModuleScssNamespace {
  export interface ICustomButtonModuleScss {
    button: string;
    large: string;
    medium: string;
    small: string;
  }
}

declare const CustomButtonModuleScssModule: CustomButtonModuleScssNamespace.ICustomButtonModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CustomButtonModuleScssNamespace.ICustomButtonModuleScss;
};

export = CustomButtonModuleScssModule;
